# -*- coding: utf-8 -*-
"""Pcitra2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSzUdio81jG3zYkDjkmZIEUG5982NUPk

Membaca dan Menampilkan Citra
"""

import cv2
import matplotlib.pyplot as plt

# Membaca citra
img = cv2.imread('bunga.jpg')

# Cek apakah citra berhasil dibaca
if img is None:
    print("Error: File tidak ditemukan!")
    exit()

# Menampilkan informasi citra
print(f"Tipe data: {img.dtype}")
print(f"Dimensi (tinggi, lebar, channel): {img.shape}")  # (h, w, c)

# Konversi BGR ke RGB agar tampil normal di matplotlib
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Menampilkan citra
plt.imshow(img_rgb)
plt.title('Citra Asli (RGB)')
plt.axis('off')
plt.show()

"""Menampilkan Nilai Piksel"""

# Ambil nilai piksel pada baris ke-100, kolom ke-150 (format BGR)
pixel = img[100, 150]
print(f"Nilai piksel pada (100,150): B={pixel[0]}, G={pixel[1]}, R={pixel[2]}")

# Tampilkan nilai saluran merah pada area tertentu (misal: baris 50-100, kolom 50-100)
red_channel = img[50:100, 50:100, 2]  # indeks 2 adalah Red dalam BGR
print(f"Nilai Red pada area crop:\n{red_channel}")

"""Konversi ke Grayscale dan HSV"""

img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Konversi ke HSV
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

# Tampilkan ketiganya dalam satu figure
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.imshow(img_rgb)
plt.title('RGB')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(img_gray, cmap='gray')
plt.title('Grayscale')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(img_hsv)  # Matplotlib akan menampilkan HSV sebagai gambar berwarna (interpretasi salah), sebaiknya gunakan cv2.imshow() atau konversi dulu
plt.title('HSV (as is)')
plt.axis('off')

plt.tight_layout()
plt.show()

"""Mengubah Ukuran Citra (Resize)"""

# Resize menjadi 300x300 piksel
img_resize = cv2.resize(img_rgb, (300, 300))

# Resize dengan faktor skala (misal 0.5 dari ukuran asli)
height, width = img_rgb.shape[:2]
img_half = cv2.resize(img_rgb, (int(width*0.5), int(height*0.5)))

# Tampilkan hasil
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(img_resize)
plt.title('Resize 300x300')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(img_half)
plt.title('Half Size')
plt.axis('off')
plt.show()

"""Rotasi dan Cropping"""

# Rotasi 90 derajat berlawanan arah jarum jam
img_rotated = cv2.rotate(img_rgb, cv2.ROTATE_90_COUNTERCLOCKWISE)

# Crop bagian tengah (misal: 100x100 dari pusat)
h, w = img_rgb.shape[:2]
start_row, start_col = h//2 - 50, w//2 - 50
img_crop = img_rgb[start_row:start_row+100, start_col:start_col+100]

# Tampilkan
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.imshow(img_rotated)
plt.title('Rotated 90°')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(img_crop)
plt.title('Crop (100x100)')
plt.axis('off')
plt.show()

"""Menyimpan Citra"""

cv2.imwrite('bunga_gray.jpg', img_gray)
cv2.imwrite('bunga_rotated.jpg', cv2.cvtColor(img_rotated, cv2.COLOR_RGB2BGR))  # simpan dalam format BGR
print("Citra berhasil disimpan.")

"""Kode Lengkap"""

import cv2
import matplotlib.pyplot as plt

def main():
    # Baca citra
    img = cv2.imread('bunga.jpg')
    if img is None:
        print("File tidak ditemukan!")
        return

    # Konversi BGR ke RGB untuk tampilan
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # 1. Informasi citra
    print(f"Dimensi: {img.shape}")
    print(f"Tipe data: {img.dtype}")

    # 2. Tampilkan citra asli
    plt.figure(figsize=(12, 6))
    plt.subplot(2, 3, 1)
    plt.imshow(img_rgb)
    plt.title('Asli (RGB)')
    plt.axis('off')

    # 3. Grayscale
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    plt.subplot(2, 3, 2)
    plt.imshow(img_gray, cmap='gray')
    plt.title('Grayscale')
    plt.axis('off')

    # 4. HSV (tampilkan saluran H saja sebagai contoh)
    img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    plt.subplot(2, 3, 3)
    plt.imshow(img_hsv[:,:,0], cmap='hsv')  # Hue channel
    plt.title('Hue Channel')
    plt.axis('off')

    # 5. Resize
    img_resize = cv2.resize(img_rgb, (200, 200))
    plt.subplot(2, 3, 4)
    plt.imshow(img_resize)
    plt.title('Resize 200x200')
    plt.axis('off')

    # 6. Rotasi
    img_rot = cv2.rotate(img_rgb, cv2.ROTATE_90_CLOCKWISE)
    plt.subplot(2, 3, 5)
    plt.imshow(img_rot)
    plt.title('Rotate 90° CW')
    plt.axis('off')

    # 7. Crop
    h, w = img_rgb.shape[:2]
    img_crop = img_rgb[h//4:3*h//4, w//4:3*w//4]
    plt.subplot(2, 3, 6)
    plt.imshow(img_crop)
    plt.title('Crop')
    plt.axis('off')

    plt.tight_layout()
    plt.show()

    # Simpan
    cv2.imwrite('bunga_gray.jpg', img_gray)
    cv2.imwrite('bunga_resize.jpg', cv2.cvtColor(img_resize, cv2.COLOR_RGB2BGR))
    print("Semua hasil telah disimpan.")

if __name__ == "__main__":
    main()

"""Latihan 1"""

import cv2
import matplotlib.pyplot as plt

# Membaca citra pemandangan.jpg
img_pemandangan = cv2.imread('pemandangan.jpg')

if img_pemandangan is not None:
    # Menampilkan dimensi dan tipe data
    print(f"Dimensi: {img_pemandangan.shape}")
    print(f"Tipe data: {img_pemandangan.dtype}")

    # Konversi ke grayscale dan simpan
    img_gray = cv2.cvtColor(img_pemandangan, cv2.COLOR_BGR2GRAY)
    cv2.imwrite('pemandangan_gray.jpg', img_gray)
    print("Citra gray telah disimpan.")

else:
    print("File pemandangan.jpg tidak ditemukan.")

"""Latihan 2"""

import cv2
import matplotlib.pyplot as plt

# Membaca citra pemandangan.jpg
img_pemandangan = cv2.imread('pemandangan_gray.jpg')

plt.hist(img_gray.ravel(), bins=256, range=[0,256])
plt.title('Histogram Pemandangan Grayscale')
plt.xlabel('Intensitas Piksel')
plt.ylabel('Frekuensi')
plt.show()

"""Latihan 3 (sedang)"""

img_bunga = cv2.imread('bunga.jpg')

if img_bunga is not None:
    img_bunga_rgb = cv2.cvtColor(img_bunga, cv2.COLOR_BGR2RGB)

    # Slicing array untuk mengambil objek bunga (asumsi rentang piksel bunga)
    # Sesuaikan koordinat start_row, end_row, start_col, end_col
    img_crop = img_bunga_rgb[100:300, 150:350]

    plt.imshow(img_crop)
    plt.title('Hasil Crop Bunga')
    plt.axis('off')
    plt.show()

"""Latihan 4 (Menantang)"""

nama_file = input("Masukkan nama file (beserta ekstensinya): ")
img_input = cv2.imread(nama_file)

if img_input is not None:
    img_rgb = cv2.cvtColor(img_input, cv2.COLOR_BGR2RGB)

    # Rotasi 180 derajat
    img_rotasi = cv2.rotate(img_rgb, cv2.ROTATE_180)

    # Menampilkan berdampingan
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.imshow(img_rgb)
    plt.title('Citra Asli')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(img_rotasi)
    plt.title('Rotasi 180°')
    plt.axis('off')
    plt.show()

    # Simpan hasil (kembalikan ke BGR terlebih dahulu)
    cv2.imwrite(f'rotated_{nama_file}', cv2.cvtColor(img_rotasi, cv2.COLOR_RGB2BGR))

"""Latihan 5"""

import numpy as np
import cv2
from google.colab.patches import cv2_imshow

img1 = cv2.imread('bunga.jpg')
img2 = cv2.imread('pemandangan.jpg')

if img1 is not None and img2 is not None:
    # Menyamakan ukuran (tinggi) agar np.hstack tidak error
    tinggi = img1.shape[0]
    lebar = img2.shape[1]
    img2_resized = cv2.resize(img2, (lebar, tinggi))

    # Gabung horizontal
    img_gabung = np.hstack((img1, img2_resized))

    cv2_imshow(img_gabung)

"""Studi Kasus"""

import cv2
import matplotlib.pyplot as plt

img_apel = cv2.imread('apel.jpg')

if img_apel is not None:
    img_apel_rgb = cv2.cvtColor(img_apel, cv2.COLOR_BGR2RGB)

    # Konversi ke HSV
    img_hsv = cv2.cvtColor(img_apel, cv2.COLOR_BGR2HSV)

    # Ekstrak channel Hue (indeks 0)
    hue_channel = img_hsv[:, :, 0]

    # Tampilkan channel Hue dan Citra Asli
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.imshow(img_apel_rgb)
    plt.title('Citra Apel Asli')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(hue_channel, cmap='gray')
    plt.title('Channel Hue')
    plt.axis('off')
    plt.show()

    # Menyimpan file terpisah
    cv2.imwrite('apel_hue.jpg', hue_channel)

    # Crop area buah (menghilangkan background)
    h, w = img_apel_rgb.shape[:2]
    # Asumsi apel ada tepat di tengah citra, kita potong sekian persen dari luar
    start_row, end_row = int(h*0.2), int(h*0.8)
    start_col, end_col = int(w*0.2), int(w*0.8)
    img_apel_crop = img_apel_rgb[start_row:end_row, start_col:end_col]

    plt.imshow(img_apel_crop)
    plt.title('Hasil Crop Apel')
    plt.axis('off')
    plt.show()
else:
    print("File apel.jpg tidak ditemukan!")

"""Tugas Mandiri"""

import cv2
import matplotlib.pyplot as plt

def tampilkan_dengan_plt(img, title="Citra"):
    if len(img.shape) == 3:
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    else:
        plt.imshow(img, cmap='gray')
    plt.title(title)
    plt.axis('off')
    plt.show()

def aplikasi_interaktif():
    plt.ion() # Aktifkan mode interaktif agar plt.show() tidak memblokir
    filepath = input("Masukkan nama file/path citra: ") # [cite: 233]
    img_asli = cv2.imread(filepath)

    if img_asli is None:
        print("Error: File tidak ditemukan!") # [cite: 243]
        return

    img_current = img_asli.copy()

    while True:
        print("\n--- Menu Manipulasi Citra ---") # [cite: 234]
        print("1: Informasi Citra") # [cite: 235]
        print("2: Konversi ke Grayscale") # [cite: 236]
        print("3: Resize") # [cite: 237]
        print("4: Rotasi") # [cite: 238]
        print("5: Crop") # [cite: 239]
        print("6: Simpan Hasil") # [cite: 240]
        print("7: Keluar") # [cite: 241]

        pilihan = input("Pilih menu (1-7): ")

        if pilihan == '1':
            print(f"Dimensi (H, W, C): {img_current.shape}")
            print(f"Tipe data: {img_current.dtype}")
            jml_channel = img_current.shape[2] if len(img_current.shape) == 3 else 1
            print(f"Jumlah channel: {jml_channel}")

        elif pilihan == '2':
            if len(img_current.shape) == 3:
                img_current = cv2.cvtColor(img_current, cv2.COLOR_BGR2GRAY)
                tampilkan_dengan_plt(img_current, "Hasil Grayscale") # [cite: 242]
            else:
                print("Citra sudah dalam format Grayscale.")

        elif pilihan == '3':
            w = int(input("Masukkan lebar baru (piksel): "))
            h = int(input("Masukkan tinggi baru (piksel): "))
            img_current = cv2.resize(img_current, (w, h))
            tampilkan_dengan_plt(img_current, f"Resize {w}x{h}") # [cite: 242]

        elif pilihan == '4':
            sudut = input("Masukkan sudut rotasi (90/180/270): ")
            if sudut == '90':
                img_current = cv2.rotate(img_current, cv2.ROTATE_90_CLOCKWISE)
            elif sudut == '180':
                img_current = cv2.rotate(img_current, cv2.ROTATE_180)
            elif sudut == '270':
                img_current = cv2.rotate(img_current, cv2.ROTATE_90_COUNTERCLOCKWISE)
            else:
                print("Sudut tidak valid!")
                continue
            tampilkan_dengan_plt(img_current, f"Rotasi {sudut}°") # [cite: 242]

        elif pilihan == '5':
            y1 = int(input("Koordinat y1 (baris mulai): "))
            y2 = int(input("Koordinat y2 (baris akhir): "))
            x1 = int(input("Koordinat x1 (kolom mulai): "))
            x2 = int(input("Koordinat x2 (kolom akhir): "))
            img_current = img_current[y1:y2, x1:x2]
            tampilkan_dengan_plt(img_current, "Hasil Crop") # [cite: 242]

        elif pilihan == '6':
            nama_simpan = input("Masukkan nama file tujuan (misal: hasil.jpg): ")
            cv2.imwrite(nama_simpan, img_current)
            print("Berhasil disimpan!")

        elif pilihan == '7':
            print("Terima kasih. Program selesai.")
            plt.ioff() # Nonaktifkan mode interaktif
            break

        else:
            print("Pilihan menu tidak tersedia.")

if __name__ == "__main__":
    aplikasi_interaktif()